export type Product = {
  id: number;
  slug: string;
  name: string;
  category: 'cabelo' | 'skincare' | 'cuidados';
  headline: string;
  hook: string;
  description: string;
  benefits: string[];
  stats: { percent: number; claim: string }[];
  price: number;
  originalPrice?: number;
  discount?: number;
  images: string[];
  badge?: string;
  featured?: boolean;
  variants?: string[];
  defaultVariant?: string;
  rating?: number;
  reviewCount?: number;
  includedItems?: string[];
  shopifyHandle?: string;
  _shopifyVariantIds?: Record<string, string>;
  _shopifyVariantPrices?: Record<string, number>;
  _defaultVariantId?: string | null;
};

export const products: Product[] = [
  {
    id: 1,
    slug: 'lumaglide-pro',
    name: 'LumaGlide Pro',
    category: 'cabelo',
    headline: 'Cabelo perfeito em menos de 5 minutos — em qualquer lugar, a qualquer hora.',
    hook: 'Escova alisadora portátil · sem fios',
    description: 'Descobre a escova alisadora sem fios LumaGlide Pro — a solução definitiva para o styling em movimento. Perfeita para retoques rápidos onde quer que estejas, esta ferramenta compacta e elegante entrega resultados de salão sem o incómodo dos cabos. Alisa e estiliza o teu cabelo sem esforço, em qualquer lugar e a qualquer hora. Liberdade total, flexibilidade e cabelo impecável em cada utilização. Os dias de mau cabelo acabaram.',
    benefits: [
      'Comodidade Portátil — cabe em qualquer mala, pronta a usar onde estiveres',
      'Liberdade Sem Fios — sem tomadas, sem cabos, sem limitações',
      'Resultado de Salão — cabelo liso e brilhante em minutos',
      'Sem Danos Térmicos — 200 milhões de iões negativos protegem cada fio',
    ],
    stats: [
      { percent: 98, claim: 'deixaram de se preocupar com maus dias de cabelo' },
      { percent: 89, claim: 'pouparam até 40 minutos no styling diário' },
      { percent: 64, claim: 'abandonaram a escova com fio' },
    ],
    price: 54.99,
    originalPrice: 69.99,
    discount: 21,
    badge: 'Mais Vendido',
    featured: true,
    rating: 4.9,
    reviewCount: 127,
    images: [
      '/products/lumaglide-pro-cover.png',
      '/products/lumaglide-pro-1.png',
      '/products/lumaglide-pro-2.png',
      '/products/lumaglide-pro-3.png',
      '/products/lumaglide-pro-4.png',
      '/products/lumaglide-pro-5.png',
    ],
    includedItems: ['Escova alisadora LumaGlide Pro', 'Cabo USB', 'Manual do utilizador'],
    defaultVariant: 'Preto',
    shopifyHandle: 'hair-straightener-brush-with-lcd-display-cordless-usb-charging-straightener-portable-mini-straightening-brush-for-home-travel',
  },
  {
    id: 2,
    slug: 'lumaglide-mini',
    name: 'LumaGlide Mini',
    category: 'cabelo',
    headline: 'Cabelo liso em qualquer lugar — sem cabo, sem tomada, sem compromisso.',
    hook: 'Versão compacta · leva para qualquer lugar',
    description: 'A LumaGlide Mini foi criada para os momentos em que precisas de um retoque rápido fora de casa, sem abrir mão da qualidade. Compacta, sem fios e recarregável via USB, aquece rapidamente até à temperatura ideal e entrega resultados lisos e brilhantes em minutos. Os três níveis de temperatura permitem adaptar o calor ao teu tipo de cabelo — do mais fino ao mais grosso — e a tampa de protecção integrada garante transporte seguro na mala, mochila ou bagagem de mão. Maus dias de cabelo fora de casa acabaram.',
    benefits: [
      'Portabilidade Total — tamanho mini que cabe em qualquer mala sem ocupar espaço',
      'Liberdade Sem Fios — bateria recarregável via USB, sem dependência de tomadas',
      'Temperatura Controlada — 3 níveis para cabelo fino, normal ou grosso',
      'Sem Dano Térmico — superfície aquecida com tecnologia de protecção da cutícula',
    ],
    stats: [
      { percent: 97, claim: 'afirmaram que resolveu os seus retoques fora de casa' },
      { percent: 91, claim: 'sentiram-se mais confiantes com o cabelo ao longo do dia' },
      { percent: 78, claim: 'levam sempre na mala em viagens' },
    ],
    price: 37.99,
    originalPrice: 49.99,
    discount: 24,
    rating: 4.8,
    reviewCount: 94,
    images: [
      '/products/lumaglide-mini-cover.png',
      '/products/lumaglide-mini-1.png',
      '/products/lumaglide-mini-2.png',
      '/products/lumaglide-mini-3.png',
      '/products/lumaglide-mini-4.png',
      '/products/lumaglide-mini-5.png',
      '/products/lumaglide-mini-6.png',
    ],
    includedItems: ['Escova alisadora LumaGlide Mini', 'Cabo USB', 'Tampa de protecção', 'Manual do utilizador'],
    defaultVariant: 'Preto',
    shopifyHandle: 'mini-pente-de-alisamento-de-cabelo-carregamento-sem-fio-portatil-multifuncional-cuidados-com-o-cabelo-nao-machuca-estilo-de-cabelo-alisador-de-cabelo',
  },
  {
    id: 3,
    slug: 'velair-pro-kit',
    name: 'VelAir Pro Kit',
    category: 'cabelo',
    headline: 'O secador profissional completo — que seca, trata e transforma numa única sessão.',
    hook: 'Secador + escova moduladora · kit 5 em 1',
    description: 'O VelAir Pro Kit não é apenas um secador de alta potência — é um sistema completo de tratamento e styling capilar. A tecnologia de iões negativos sela a cutícula durante a secagem, eliminando o frisado e acrescentando brilho natural. A luz de colagénio integrada intensifica o cuidado em cada passagem. Com controlo termostático preciso e cinco bocais intercambiáveis incluídos — concentrador, difusor, volume, precisão e finalização com ar frio — o VelAir Pro Kit adapta-se a qualquer tipo de cabelo, qualquer técnica e qualquer resultado pretendido. Mais de 10.000 clientes já fizeram a troca. A diferença no cabelo é visível desde a primeira utilização.',
    benefits: [
      'Secagem Ultra-Rápida — 1600–1999W que reduz o tempo de exposição ao calor',
      'Tecnologia Iónica — sela a cutícula, elimina o frisado e amplifica o brilho',
      'Temperatura Constante — termostato preciso sem flutuações que danificam o fio',
      'Kit Completo 5 em 1 — 5 bocais + suporte de mesa, tudo num único investimento',
    ],
    stats: [
      { percent: 96, claim: 'notaram redução visível do frisado desde a primeira utilização' },
      { percent: 88, claim: 'cabelo mais brilhante e saudável ao longo do tempo' },
      { percent: 73, claim: 'reduziram o tempo de secagem em mais de metade' },
    ],
    price: 72.99,
    originalPrice: 94.99,
    discount: 23,
    badge: 'Novo',
    rating: 4.8,
    reviewCount: 83,
    images: [
      '/products/velair-cover.png',
      '/products/velair-1.png',
      '/products/velair-2.png',
      '/products/velair-3.png',
    ],
    includedItems: ['Secador VelAir Pro', 'Bocal concentrador', 'Bocal difusor', 'Bocal de precisão', 'Bocal de volume', 'Bocal de finalização com ar frio', 'Suporte de mesa', 'Manual do utilizador'],
    shopifyHandle: 'secador-de-cabelo-profissional-5-em-1-com-funcionalidade-de-ar-quente-e-frio-ferramenta-de-estilo-leve-e-termostatica-para-cabelos-lisos',
  },
  {
    id: 4,
    slug: 'kipozi-titanium',
    name: 'KIPOZI Titanium',
    category: 'cabelo',
    headline: 'Titânio, temperatura precisa e voltagem universal — para cabelo sério.',
    hook: 'Placas de titânio · 230°C · LCD',
    description: 'O ferro KIPOZI Titanium foi concebido para quem usa ferro com regularidade e sabe que a qualidade das placas muda tudo. O titânio aquece mais rápido, mantém a temperatura mais estável e desliza com uma suavidade que o cerâmico convencional não consegue replicar. O ecrã LCD mostra a temperatura exacta de trabalho em tempo real — sem adivinhações, sem risco de sobreaquecimento. A voltagem dual 110V–240V torna-o completamente universal, do Porto a Nova Iorque, passando pelo Brasil. Um ferro de nível profissional que veio para ficar na bancada — não na gaveta.',
    benefits: [
      'Placas de Titânio — aquecimento rápido, temperatura estável, deslize excepcional',
      'Ecrã LCD de Precisão — temperatura em tempo real, controlo total sobre cada passagem',
      'Voltagem Universal — 110V–240V sem transformador para qualquer destino do mundo',
      'Multifunções — alisa, ondula e cria caracóis com a mesma ferramenta',
    ],
    stats: [
      { percent: 95, claim: 'cabelo mais liso e brilhante com menos passagens' },
      { percent: 87, claim: 'o ecrã LCD mudou a forma como usam o ferro' },
      { percent: 79, claim: 'levam o KIPOZI em todas as viagens internacionais' },
    ],
    price: 64.99,
    originalPrice: 79.99,
    discount: 18,
    rating: 4.7,
    reviewCount: 112,
    images: [
      '/products/kipozi-cover.png',
      '/products/kipozi-1.png',
      '/products/kipozi-2.png',
      '/products/kipozi-3.png',
    ],
    includedItems: ['Ferro alisador KIPOZI Titanium', 'Luva de protecção térmica', 'Manual do utilizador'],
    shopifyHandle: 'kipocozi-alisador-de-cabelo-profissional-de-ferro-plano-de-titanio-com-display-lcd-digital-ferro-de-ondulacao-de-aquecimento-instantaneo-de-tensao-dupla',
  },
  {
    id: 5,
    slug: 'ritmostyler-pro',
    name: 'RitmoStyler Pro',
    category: 'cabelo',
    headline: 'Uma estação de styling completa — que seca, alisa, modela e cuida ao mesmo tempo.',
    hook: 'Modelador multi-ponta 5 em 1',
    description: 'O RitmoStyler Pro não é um secador com bocais. É uma estação de styling completa com acessórios aquecidos activos que trabalham em simultâneo com o fluxo de ar, replicando o resultado que antes só conseguias no salão. O secador iónico integrado seca em poucos minutos enquanto os pentes e escovas aquecidos moldam, volumizam e alisam o cabelo com precisão — tudo num único movimento. A tecnologia de iões negativos sela a cutícula durante o processo, entregando cabelo macio, sem frisado e com brilho natural. Voltagem universal, motor silencioso e design de estação pensado para quem quer o melhor resultado — na bancada de casa.',
    benefits: [
      'Sistema 5 em 1 — secagem, alisamento, volume, modelação e finalização num único kit',
      'Acessórios Aquecidos Activos — pentes e escovas com calor próprio para styling simultâneo',
      'Tecnologia Iónica — elimina o frisado e deixa o cabelo brilhante desde a primeira sessão',
      'Motor Silencioso — alta potência sem o ruído elevado dos secadores convencionais',
    ],
    stats: [
      { percent: 94, claim: 'resultado que iguala ou supera o styling no salão' },
      { percent: 86, claim: 'reduziram o tempo total de styling em mais de 30 min/semana' },
      { percent: 71, claim: 'eliminaram pelo menos duas ferramentas de styling' },
    ],
    price: 84.99,
    originalPrice: 109.99,
    discount: 22,
    featured: true,
    rating: 4.8,
    reviewCount: 76,
    images: [
      '/products/ritmostyler-cover.png',
      '/products/ritmostyler-1.png',
      '/products/ritmostyler-2.png',
      '/products/ritmostyler-3.png',
      '/products/ritmostyler-4.png',
      '/products/ritmostyler-5.png',
    ],
    includedItems: ['Corpo do secador iónico', 'Pente aquecido para alisamento', 'Escova de volume aquecida', 'Acessório de modelação', 'Difusor', 'Manual do utilizador'],
    shopifyHandle: 'profissional-cabelo-styler-set-5-em-1-alta-velocidade-hot-comb-escova-secagem-rapida-ionic-alisador-secador-poderoso',
  },
  {
    id: 6,
    slug: 'essencia-mucina-caracol',
    name: 'Essência de Mucina de Caracol',
    category: 'skincare',
    headline: 'A fórmula de reparação mais estudada do skin care — agora na tua rotina.',
    hook: '100 ml · regeneração noturna',
    description: 'Esta essência concentra 96% de filtrado de secreção de caracol — um dos activos mais estudados e clinicamente validados do skin care coreano — combinado com ácido hialurónico e vitamina E numa fórmula de reparação intensiva. Com uso regular, actua nas camadas mais profundas da epiderme: restaura a barreira cutânea, atenua linhas de expressão, devolve firmeza natural e mantém a pele hidratada ao longo de todo o dia. A textura fluida absorve rapidamente, sem resíduos oleosos e sem desconforto. A pele que parecia precisar de tratamento — começa a mostrar a diferença.',
    benefits: [
      'Mucina de Caracol a 96% — repara, regenera e fortalece a barreira cutânea com eficácia comprovada',
      'Ácido Hialurónico — hidratação profunda e duradoura nas camadas mais internas da pele',
      'Acção Anti-Rugas — atenua linhas de expressão e melhora a elasticidade com uso continuado',
      'Vitamina E Antioxidante — protege as células do envelhecimento causado por agentes externos',
    ],
    stats: [
      { percent: 93, claim: 'pele mais hidratada e suave em menos de duas semanas' },
      { percent: 85, claim: 'redução visível de linhas finas após 30 dias' },
      { percent: 77, claim: 'tornou-se o produto insubstituível da rotina' },
    ],
    price: 16.49,
    originalPrice: 22.99,
    discount: 28,
    featured: true,
    rating: 4.9,
    reviewCount: 143,
    images: [
      '/products/essencia-cover.png',
      '/products/essencia-1.png',
      '/products/essencia-2.png',
    ],
    includedItems: ['Frasco de essência de mucina de caracol', 'Manual de utilização'],
    shopifyHandle: 'caracol-96-mucina-power-essencia-desbotamento-linhas-finas-hidratante-levantamento-endurecimento-suavizacao-nutrin-brilho-cuidados-com-a-pele',
  },
  {
    id: 7,
    slug: 'serum-pdrn-olheiras',
    name: 'Sérum PDRN para Olheiras',
    category: 'skincare',
    headline: 'O activo da medicina estética — agora no teu ritual de cuidado diário.',
    hook: '30 ml · contorno dos olhos',
    description: 'O PDRN — polinucleótido derivado de ADN de salmão — era até há pouco exclusivo das clínicas de medicina estética. Este sérum coreano traz esse activo de regeneração celular para o uso diário, combinado com péptidos de rosa numa textura rosada e sedosa que transforma a rotina de cuidado. Actua em múltiplas frentes: repara as células danificadas, atenua as manchas escuras e olheiras, hidrata em profundidade e melhora progressivamente a firmeza e luminosidade da pele. Com uso regular, a tez ganha a uniformidade que antes demorava meses a alcançar. A skin care coreana chegou onde a estética convencional demorava a chegar.',
    benefits: [
      'PDRN de ADN de Salmão — regenera células, repara tecidos e activa a síntese de colagénio',
      'Péptidos de Rosa — estimulam a firmeza e combatem a flacidez progressiva',
      'Anti-Manchas — uniformiza o tom da pele e atenua as manchas escuras',
      'Hidratação Intensa — textura fluida que penetra rapidamente e mantém a pele hidratada',
    ],
    stats: [
      { percent: 91, claim: 'melhoria visível na luminosidade e uniformidade após 3 semanas' },
      { percent: 83, claim: 'redução nas olheiras e manchas escuras' },
      { percent: 76, claim: 'pele progressivamente mais firme e resistente' },
    ],
    price: 16.69,
    originalPrice: 22.99,
    discount: 27,
    badge: 'Novo',
    rating: 4.8,
    reviewCount: 98,
    images: [
      '/products/serum-pdrn-cover.png',
      '/products/serum-pdrn-1.png',
      '/products/serum-pdrn-2.png',
      '/products/serum-pdrn-3.png',
      '/products/serum-pdrn-4.webp',
    ],
    includedItems: ['Frasco de sérum PDRN', 'Manual de utilização'],
    shopifyHandle: 'salmao-dna-pdrn-rosa-peptideo-soro-brilho-rosa-remover-escuridao-da-pele-hidratante-hidratante-endurecimento-coreano-cuidados-com-a-pele',
  },
  {
    id: 8,
    slug: 'milk-glow-tonico',
    name: 'Milk Glow Tónico',
    category: 'skincare',
    headline: 'O passo que a tua rotina de skin care precisava — mas que ainda não tinha.',
    hook: '150 ml · hidratação diária',
    description: 'O Milk Glow Tónico é o passo mais subestimado da skin care — e o que, quando adicionado, muda o resultado de tudo o que se aplica depois. Não é água com fragrância. É o que repõe a humidade perdida durante a limpeza, equilibra o pH e prepara a pele para absorver séruns e hidratantes com máxima eficácia. Inspirado no formato "milk toner" do skin care coreano, combina ingredientes que hidratam, iluminam e suavizam a textura em simultâneo. A pele fica imediatamente mais macia ao toque, mais uniforme ao olhar e pronta para receber os activos seguintes. Com uso regular, a tez ganha aquela luminosidade natural — "glow" — que os séruns sozinhos não conseguem criar.',
    benefits: [
      'Hidratação de 24 Horas — barreira de humidade que mantém a pele hidratada ao longo do dia',
      'Efeito Glow Natural — ilumina o tom da pele sem partículas ou efeito artificial',
      'Textura Milk Toner — leitosa, ultra-fluida e de absorção imediata',
      'Amplifica os Activos Seguintes — prepara a pele para absorver séruns e cremes com o dobro da profundidade',
    ],
    stats: [
      { percent: 94, claim: 'pele mais hidratada e luminosa logo nas primeiras utilizações' },
      { percent: 87, claim: 'séruns e cremes passaram a ser mais eficazes' },
      { percent: 81, claim: 'tornaram-no insubstituível da rotina de skin care' },
    ],
    price: 16.99,
    originalPrice: 22.99,
    discount: 26,
    rating: 4.7,
    reviewCount: 89,
    images: [
      '/products/milk-glow-cover.png',
      '/products/milk-glow-1.png',
      '/products/milk-glow-2.png',
      '/products/milk-glow-3.png',
    ],
    includedItems: ['Frasco de tónico Milk Glow', 'Manual de utilização'],
    shopifyHandle: 'leche-brilho-toner-iluminando-a-pele-hidrata-poderosa-aliviar-a-pele-seca-e-cansada-bloqueia-em-umidade-beleza-cuidados-com-a-pele-100ml',
  },
  {
    id: 9,
    slug: 'mascara-biocolagenio',
    name: 'Máscara Facial Bio-Colagénio 5 pcs',
    category: 'skincare',
    headline: 'Acorda com a pele que querias ter quando te deitaste.',
    hook: '5 unidades · efeito imediato',
    description: 'A Máscara Facial Bio-Colagénio foi concebida para a janela de reparação que nenhum produto diurno consegue replicar: a noite. Aplica-se como último passo da rotina, adere ao rosto como uma segunda pele e liberta activos de bio-colagénio de forma contínua durante horas. A textura de hidrogel elimina o problema das máscaras convencionais: não escorre, não mancha a almofada, não causa desconforto. De manhã, a pele está visivelmente mais suave, mais firme e com aquele aspecto de descanso que às vezes a rotina diária não consegue criar. Mais de 10.000 vendas — porque o resultado fala antes de qualquer descrição.',
    benefits: [
      'Bio-Colagénio em Hidrogel — libertação lenta e contínua durante toda a noite para firmeza real',
      'Hidratação Overnight — penetração profunda sem interferência das condições externas',
      'Firmeza Progressiva — elasticidade melhorada com uso regular de 2-3 vezes por semana',
      'Hidrogel de Aderência Total — não escorre, não mancha, confortável durante toda a noite',
    ],
    stats: [
      { percent: 96, claim: 'acordaram com pele visivelmente mais hidratada e suave' },
      { percent: 88, claim: 'melhoria progressiva na firmeza após 4 semanas' },
      { percent: 82, claim: 'tornaram-na parte permanente do ritual semanal' },
    ],
    price: 17.49,
    originalPrice: 24.99,
    discount: 30,
    badge: 'Pack 5',
    rating: 4.9,
    reviewCount: 201,
    images: [
      '/products/mascara-cover.webp',
      '/products/mascara-1.png',
      '/products/mascara-2.png',
      '/products/mascara-3.png',
      '/products/mascara-4.png',
    ],
    includedItems: ['5 máscaras faciais de hidrogel Bio-Colagénio', 'Instruções de utilização'],
    shopifyHandle: 'bio-colageno-mascara-profunda-real-suplemento-colageno-hidratante-durante-a-noite-mascara-de-hidrogel-melhoria-da-elasticidade-poros-minimizando-endurecimento',
  },
  {
    id: 10,
    slug: 'eelhoe-centella-oleo-limpeza',
    name: 'Eelhoe Centella Óleo de Limpeza',
    category: 'skincare',
    headline: 'A desmaquilhagem que também cuida — um passo que faz dois.',
    hook: '200 ml · primeira etapa',
    description: 'O Eelhoe Centella Óleo de Limpeza faz o que a água micelar não consegue: remove toda a maquilhagem, o protector solar e as impurezas oleosas com uma eficácia que os produtos aquosos nunca igualam — enquanto deixa a pele macia, confortável e preparada para os passos seguintes. A fórmula combina centella asiatica com vitamina E: a centella calma e repara; a vitamina E nutre e protege. Em contacto com a água, transforma-se em emulsão leitosa que enxagua completamente sem resíduos — sem a sensação oleosa que afasta tantas pessoas do cleansing oil. O primeiro passo do double cleansing coreano — e o passo que muda tudo o que a pele absorve a seguir.',
    benefits: [
      'Centella Asiatica — calma, reduz vermelhidão e fortalece a barreira cutânea',
      'Vitamina E — nutre e protege durante a desmaquilhagem',
      'Emulsificação Total — enxagua completamente sem resíduos oleosos',
      'Double Cleansing — primeiro passo ideal do método de limpeza coreano em dois tempos',
    ],
    stats: [
      { percent: 95, claim: 'remove maquilhagem mais eficazmente do que qualquer anterior' },
      { percent: 87, claim: 'pele mais calmada e menos irritada após substituir a água micelar' },
      { percent: 79, claim: 'adicionaram o double cleansing permanentemente à rotina' },
    ],
    price: 17.92,
    originalPrice: 24.99,
    discount: 28,
    rating: 4.8,
    reviewCount: 115,
    images: [
      '/products/eelhoe-cover.png',
      '/products/eelhoe-1.png',
      '/products/eelhoe-2.png',
    ],
    includedItems: ['Frasco de óleo de limpeza Centella', 'Manual de utilização'],
    shopifyHandle: 'centella-oleo-de-limpeza-removedor-de-maquiagem-suave-limpeza-facial-hidratante-vitamina-e-controle-de-oleo-encolher-poros-produtos-de-cuidados-com-a-pele',
  },
  {
    id: 11,
    slug: 'rosemary-hair-oil',
    name: 'Eelhoe Rosemary Hair Oil',
    category: 'cuidados',
    headline: 'O activo validado pela ciência para crescimento capilar — num frasco.',
    hook: 'Óleo de alecrim · estimula crescimento',
    description: 'O alecrim não é uma tendência passageira. Um ensaio clínico publicado em SKINmed comparou o óleo de alecrim com minoxidil 2% durante seis meses em doentes com alopécia androgenética — com resultados equivalentes, sem os efeitos secundários. O Eelhoe Rosemary Hair Oil concentra o extracto puro de alecrim (Rosmarinus Officinalis) num formato de aplicação directa no couro cabeludo: gotas precisas que estimulam a microcirculação, fortalecem a raiz e ajudam a reduzir a queda progressiva. A fórmula leve absorve sem pesar o fio. Mais de 10.000 pessoas já começaram a crescer — com uma rotina de dois minutos por dia.',
    benefits: [
      'Alecrim Clinicamente Validado — activo com estudos comparativos ao minoxidil 2% publicados',
      'Estimulação Folicular — melhora o fluxo sanguíneo no couro cabeludo para crescimento activo',
      'Anti-Queda Progressivo — redução da queda e aparecimento de novos fios com uso regular',
      'Fórmula Leve — sem resíduos, sem gordura visível, sem alterar a textura do cabelo',
    ],
    stats: [
      { percent: 89, claim: 'redução visível da queda capilar após 6 semanas' },
      { percent: 81, claim: 'aumento de densidade e volume na zona de maior queda' },
      { percent: 74, claim: 'tornou-se a parte mais importante do ritual capilar' },
    ],
    price: 14.99,
    originalPrice: 19.99,
    discount: 25,
    featured: true,
    rating: 4.9,
    reviewCount: 167,
    images: [
      '/products/rosemary-cover.png',
      '/products/rosemary-1.png',
      '/products/rosemary-2.png',
    ],
    includedItems: ['Frasco de óleo de alecrim com conta-gotas', 'Manual de utilização'],
    shopifyHandle: 'eelhoe-oleo-essencial-de-alecrim-reparacao-cabelo-danificado-alisamento-tratamento-anti-calvicie-tratamento-do-couro-cabeludo-nutritivo-oleo-de-crescimento-do-cabelo',
  },
  {
    id: 12,
    slug: 'turbante-microfibra',
    name: 'Turbante de Microfibras',
    category: 'cuidados',
    headline: 'O cabelo que demorava 40 minutos a secar — agora seca em 10.',
    hook: 'Secagem rápida · 3 cores',
    description: 'O turbante de microfibra Lumara absorve a água até três vezes mais rápido que uma toalha convencional — sem esfregar, sem atrito, sem quebra. A microfibra ultra-absorvente funciona por capilaridade: encapsula as moléculas de água e retira-as do fio sem contacto mecânico que danifica a cutícula. O formato turbante mantém o cabelo seguro e livre enquanto fazes a rotina de cuidado, a maquilhagem ou qualquer outra coisa. O fecho ajustável adapta-se a qualquer tamanho de cabeça sem marcar nem apertar. Uma mudança pequena na rotina com impacto real na saúde do cabelo a longo prazo.',
    benefits: [
      'Absorção 3x Superior — absorve 3x mais do que uma toalha convencional sem esfregar',
      'Sem Atrito — preserva a cutícula intacta, reduz frisado e quebra',
      'Formato Turbante — fica preso sozinho e liberta as mãos',
      'Ideal para cabelo tratado, colorido, ondulado e encaracolado',
    ],
    stats: [
      { percent: 97, claim: 'redução do frisado e tempo de secagem desde a primeira utilização' },
      { percent: 91, claim: 'cabelo mais definido e saudável' },
      { percent: 84, claim: 'eliminaram a toalha convencional do ritual capilar' },
    ],
    price: 16.95,
    originalPrice: 24.99,
    discount: 32,
    rating: 4.7,
    reviewCount: 88,
    images: [
      '/products/turbante-cover.png',
      '/products/turbante-1.png',
    ],
    includedItems: ['Turbante de microfibra (1 unidade)', 'Instruções de cuidado e lavagem'],
    shopifyHandle: 'toalha-absorvente-para-cabelo-em-cor-solida-9-8-x-25-5-capuz-texturizado-para-secar-cabelo-para-mulheres',
  },
  {
    id: 13,
    slug: 'touca-cetim-lumara',
    name: 'Touca de Cetim Lumara',
    category: 'cuidados',
    headline: 'A noite que o teu cabelo passou a aproveitar — em vez de desperdiçar.',
    hook: 'Protege o cabelo à noite · 3 cores',
    description: 'A fronha de algodão absorve a humidade do fio durante a noite e cria fricção que embaraça, fragmenta os caracóis e abre a cutícula. O resultado acumula-se ao longo do tempo — e traduz-se em cabelo que parece estar sempre a precisar de tratamento. A touca de cetim Lumara elimina esse problema na origem. O tecido acetinado cria uma superfície de baixa fricção que protege o fio durante o sono: mantém a humidade dos produtos aplicados antes de dormir, preserva a definição e evita a quebra. O tamanho grande acomoda tranças, box braids, dreadlocks e cabelo volumoso com conforto. Uma mudança de três segundos na rotina nocturna que muda o estado do cabelo de manhã.',
    benefits: [
      'Protecção Nocturna Total — cetim que preserva a humidade e a definição durante toda a noite',
      'Tamanho Grande — acomoda qualquer volume de cabelo, incluindo tranças e box braids',
      'Retém Produtos — o cetim não absorve os produtos aplicados antes de dormir',
      'Banda Regulável — ajusta ao tamanho da cabeça sem marcar durante a noite',
    ],
    stats: [
      { percent: 96, claim: 'redução significativa do frisado matinal desde a primeira noite' },
      { percent: 89, claim: 'hidratação e produtos duraram mais após começar a usar' },
      { percent: 83, claim: 'tornaram-na parte permanente da rotina nocturna' },
    ],
    price: 18.89,
    originalPrice: 24.99,
    discount: 24,
    rating: 4.8,
    reviewCount: 132,
    images: [
      '/products/touca-cover.png',
      '/products/touca-preta-1.png',
      '/products/touca-preta-2.png',
      '/products/touca-preta-3.png',
      '/products/touca-rosa-1.png',
      '/products/touca-rosa-2.png',
      '/products/touca-rosa-3.png',
      '/products/touca-bege-1.png',
      '/products/touca-bege-2.png',
    ],
    variants: ['Rosa', 'Preta', 'Bege'],
    includedItems: ['Touca de cetim Lumara (1 unidade)', 'Instruções de cuidado'],
    shopifyHandle: 'novo-feminino-grande-gorro-de-cetim-sedoso-noite-touca-de-dormir-com-faixa-elastica-touca-de-banho-encaracolado-tranca-cabelo-cabeca-capa-turbante',
  },
  {
    id: 14,
    slug: 'fronha-seda-lumara',
    name: 'Fronha de Seda Lumara',
    category: 'cuidados',
    headline: 'O cuidado que acontece enquanto dormes — sem fazer nada.',
    hook: 'Seda 100% · menos frizz',
    description: 'A fronha de algodão convencional absorve a humidade do cabelo e da pele durante a noite, cria fricção que embaraça os fios, abre a cutícula e contribui para o surgimento de marcas no rosto ao acordar. Não é um problema que os produtos de cuidado resolvem — é um problema de superfície. E a superfície é trocável. Esta fronha de seda 100% cria uma superfície de deslizamento suave que elimina o atrito nocturno: o cabelo mantém a hidratação dos produtos aplicados antes de dormir, a cutícula fica selada e os caracóis preservam a definição. A pele desliza sobre a seda em vez de ser comprimida contra o algodão — o que se traduz em menos marcas ao acordar. Disponível em mais de quinze cores e dois tamanhos: a mudança mais simples da rotina de beleza.',
    benefits: [
      'Seda 100% — superfície ultra-suave que elimina o atrito no cabelo e na pele',
      'Preserva a Hidratação — não absorve os produtos nem a humidade do cabelo',
      'Protege os Caracóis — reduz o frisado e preserva o styling da noite anterior',
      'Gentil para a Pele — menos marcas ao acordar, menos irritação para peles sensíveis',
    ],
    stats: [
      { percent: 95, claim: 'redução das marcas no rosto ao acordar desde a primeira semana' },
      { percent: 88, claim: 'cabelo mais hidratado e definido de manhã' },
      { percent: 82, claim: 'tornaram a fronha insubstituível no ritual de beleza nocturno' },
    ],
    price: 22.97,
    originalPrice: 29.99,
    discount: 23,
    rating: 4.8,
    reviewCount: 109,
    images: [
      '/products/fronha-cover.png',
      '/products/fronha-1.png',
      '/products/fronha-2.png',
      '/products/fronha-3.png',
    ],
    variants: ['51×66 cm', '51×76 cm'],
    includedItems: ['Fronha de seda 100% (1 unidade)', 'Instruções de lavagem e cuidado'],
    shopifyHandle: '100-fronha-de-seda-capa-de-almofada-de-cetim-de-seda-beleza-fronha-confortavel-fronha-decoracao-para-casa-capas-de-almofada',
  },
];

export const driveImage = (path: string | undefined | null) => {
  if (!path) return undefined;
  if (path.startsWith('http://') || path.startsWith('https://') || path.startsWith('/')) return path;
  return `https://drive.google.com/uc?export=view&id=${path}`;
};

export const byCategory = (cat: Product['category']) =>
  products.filter((p) => p.category === cat);

export const featuredProducts = products.filter((p) => p.featured);
